version: "3.8"

services:

  backend:
    build: ./backend
    container_name: banking_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./banking.db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - redis
    networks:
      - banking_net

  worker:
    build: ./backend
    container_name: banking_worker
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - ./backend:/app
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./banking.db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - backend
    networks:
      - banking_net

  frontend:
    build: ./BankingSystem
    container_name: banking_frontend
    ports:
      - "5173:3000"
    networks:
      - banking_net

  redis:
    image: redis:alpine
    container_name: banking_redis
    ports:
      - "6379:6379"
    networks:
      - banking_net

  prometheus:
    image: prom/prometheus
    container_name: banking_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - banking_net

  grafana:
    image: grafana/grafana
    container_name: banking_grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - banking_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: banking_elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - banking_net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: banking_logstash
    volumes:
      - ./backend/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
    networks:
      - banking_net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: banking_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - banking_net

networks:
  banking_net:
    driver: bridge
