input {
  file {
    path => "/usr/share/logstash/logs/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "banking-logs-%{+YYYY.MM.dd}"
  }
}
